/* Copyright 2009-2011 Hewlett-Packard Development Company, L.P. All rights reserved. */
/*$
 * @name countryNames.js
 * @fileOverview dummy file for localization -- do not list this file in the manifest.json!
 * 
 * Copyright (c) 2010 Palm, Inc.  All rights reserved.
 */


$L("afghanistan");
$L("aland islands");
$L("åland islands");
$L("albania");
$L("algeria");
$L("american samoa");
$L("andorra");
$L("angola");
$L("anguilla");
$L("antarctica");
$L("antigua and barbuda");
$L("antigua & barbuda");
$L("antigua");
$L("barbuda");
$L("argentina");
$L("armenia");
$L("aruba");
$L("australia");
$L("austria");
$L("azerbaijan");
$L("bahamas");
$L("the bahamas");
$L("bahrain");
$L("bangladesh");
$L("barbados");
$L("belarus");
$L("belgium");
$L("belize");
$L("benin");
$L("bermuda");
$L("bhutan");
$L("bolivia, plurinational state of");
$L("plurinational state of bolivia");
$L("bolivia");
$L("bosnia and herzegovina");
$L("bosnia & herzegovina");
$L("bosnia");
$L("herzegovina");
$L("botswana");
$L("bouvet island");
$L("brazil");
$L("british indian ocean territory");
$L("brunei darussalam");
$L("brunei");
$L("bulgaria");
$L("burkina faso");
$L("burundi");
$L("cambodia");
$L("cameroon");
$L("canada");
$L("cape verde");
$L("cape verde islands");
$L("cayman islands");
$L("caymans");
$L("central african republic");
$L("car");
$L("c.a.r.");
$L("chad");
$L("chile");
$L("people's republic of china");
$L("p. r. of china");
$L("p. r. china");
$L("p.r. of china");
$L("pr china");
$L("prc");
$L("china");
$L("christmas island");
$L("cocos (keeling) islands");
$L("cocos islands");
$L("cocos and keeling islands");
$L("cocos & keeling islands");
$L("cocos");
$L("colombia");
$L("comoros");
$L("congo");
$L("congo, the democratic republic of the");
$L("congo, democratic republic of the");
$L("the democratic republic of the congo");
$L("democratic republic of the congo");
$L("drc");
$L("d.r.c.");
$L("congo");
$L("cook islands");
$L("costa rica");
$L("cote d'ivoire");
$L("côte d'ivoire");
$L("ivory coast");
$L("croatia");
$L("cuba");
$L("cyprus");
$L("the czech republic");
$L("czech republic");
$L("denmark");
$L("djibouti");
$L("dominica");
$L("dominican republic");
$L("dr");
$L("d.r.");
$L("ecuador");
$L("egypt");
$L("el salvador");
$L("equatorial guinea");
$L("eritrea");
$L("estonia");
$L("ethiopia");
$L("falkland islands");
$L("falklands");
$L("malvinas");
$L("faroe islands");
$L("faroes");
$L("fiji");
$L("finland");
$L("france");
$L("french guiana");
$L("french polynesia");
$L("polynesia");
$L("french southern territories");
$L("gabon");
$L("gambia");
$L("georgia");
$L("germany");
$L("ghana");
$L("gibraltar");
$L("greece");
$L("greenland");
$L("grenada");
$L("guadeloupe");
$L("guam");
$L("guatemala");
$L("guernsey");
$L("guinea");
$L("guinea-bissau");
$L("guyana");
$L("haiti");
$L("heard island and mcdonald islands");
$L("heard island & mcdonald islands");
$L("heard and mcdonald islands");
$L("heard island");
$L("mcdonald islands");
$L("holy see");
$L("vatican city state");
$L("vatican city");
$L("vatican");
$L("honduras");
$L("hong kong");
$L("hungary");
$L("iceland");
$L("india");
$L("indonesia");
$L("iran, islamic republic of");
$L("islamic republic of iran");
$L("iran");
$L("iraq");
$L("republic of ireland");
$L("ireland");
$L("éire");
$L("isle of man");
$L("israel");
$L("italy");
$L("jamaica");
$L("japan");
$L("jersey");
$L("jordan");
$L("kazakhstan");
$L("kenya");
$L("kiribati");
$L("korea, democratic people's republic of");
$L("democratic people's republic of korea");
$L("dprk");
$L("north korea");
$L("korea, republic of");
$L("republic of korea");
$L("south korea");
$L("korea");
$L("kuwait");
$L("kyrgyzstan");
$L("lao people's democratic republic");
$L("laos");
$L("latvia");
$L("lebanon");
$L("lesotho");
$L("liberia");
$L("libyan arab jamahiriya");
$L("libya");
$L("liechtenstein");
$L("lithuania");
$L("luxembourg");
$L("macao");
$L("macedonia, the former yugoslav republic of");
$L("macedonia, former yugoslav republic of");
$L("the former yugoslav republic of macedonia");
$L("former yugoslav republic of macedonia");
$L("fyrom");
$L("f.y.r.o.m.");
$L("republic of macedonia");
$L("macedonia");
$L("madagascar");
$L("malawi");
$L("malaysia");
$L("maldives");
$L("mali");
$L("malta");
$L("marshall islands");
$L("marshalls");
$L("martinique");
$L("mauritania");
$L("mauritius");
$L("mayotte");
$L("mexico");
$L("micronesia, federated states of");
$L("federated states of micronesia");
$L("micronesia");
$L("moldova, republic of");
$L("republic of moldova");
$L("moldova");
$L("monaco");
$L("mongolia");
$L("montenegro");
$L("montserrat");
$L("morocco");
$L("mozambique");
$L("myanmar");
$L("namibia");
$L("nauru");
$L("nepal");
$L("holland");
$L("netherlands antilles");
$L("the netherlands");
$L("netherlands");
$L("new caledonia");
$L("new zealand");
$L("nicaragua");
$L("niger");
$L("nigeria");
$L("niue");
$L("norfolk island");
$L("northern mariana islands");
$L("marianas");
$L("norway");
$L("oman");
$L("pakistan");
$L("palau");
$L("palestinian territory, occupied");
$L("occupied palestinian territory");
$L("palestinian territory");
$L("palestinian authority");
$L("palestine");
$L("panama");
$L("papua new guinea");
$L("png");
$L("paraguay");
$L("peru");
$L("the philippines");
$L("philippines");
$L("pitcairn");
$L("poland");
$L("portugal");
$L("puerto rico");
$L("qatar");
$L("reunion");
$L("réunion");
$L("romania");
$L("russian federation");
$L("russia");
$L("rwanda");
$L("saint barthélemy");
$L("st. barthélemy");
$L("saint barthelemy");
$L("saint barts");
$L("st barthélemy");
$L("st. barthelemy");
$L("st barthelemy");
$L("st. barts");
$L("st barts");
$L("saint helena, ascension and tristan da cunha");
$L("saint helena, ascension & tristan da cunha");
$L("saint helena");
$L("st. helena, ascension and tristan da cunha");
$L("st. helena, ascension & tristan da cunha");
$L("st. helena");
$L("st helena, ascension and tristan da cunha");
$L("st helena, ascension & tristan da cunha");
$L("st helena");
$L("ascension");
$L("tristan da cunha");
$L("saint kitts and nevis");
$L("saint kitts & nevis");
$L("saint kitts");
$L("st. kitts and nevis");
$L("st. kitts & nevis");
$L("st. kitts");
$L("st kitts and nevis");
$L("st kitts & nevis");
$L("st kitts");
$L("nevis");
$L("saint lucia");
$L("st. lucia");
$L("st lucia");
$L("saint martin");
$L("st. martin");
$L("st martin");
$L("saint pierre and miquelon");
$L("saint pierre & miquelon");
$L("saint pierre");
$L("st. pierre and miquelon");
$L("st. pierre & miquelon");
$L("st. pierre");
$L("st pierre and miquelon");
$L("st pierre & miquelon");
$L("st pierre");
$L("miquelon");
$L("saint vincent and the grenadines");
$L("saint vincent & the grenadines");
$L("saint vincent");
$L("st. vincent and the grenadines");
$L("st. vincent & the grenadines");
$L("st. vincent");
$L("st vincent and the grenadines");
$L("st vincent & the grenadines");
$L("st vincent");
$L("the grenadines");
$L("grenadines");
$L("samoa");
$L("san marino");
$L("sao tome and principe");
$L("sao tome & principe");
$L("sao tome");
$L("principe");
$L("saudi arabia");
$L("arabia");
$L("senegal");
$L("sénégal");
$L("serbia");
$L("seychelles");
$L("sierra leone");
$L("the republic of singapore");
$L("republic of singapore");
$L("singapore");
$L("slovakia");
$L("slovenia");
$L("solomon islands");
$L("solomons");
$L("somalia");
$L("south africa");
$L("south georgia and the south sandwich islands");
$L("south georgia & the south sandwich islands");
$L("south georgia");
$L("the south sandwich islands");
$L("south sandwich islands");
$L("spain");
$L("sri lanka");
$L("the sudan");
$L("sudan");
$L("suriname");
$L("svalbard and jan mayen");
$L("svalbard & jan mayen");
$L("svalbard");
$L("jan mayen");
$L("swaziland");
$L("sweden");
$L("switzerland");
$L("syrian arab republic");
$L("syria");
$L("taiwan, province of china");
$L("republic of china");
$L("taiwan");
$L("R.O.C.");
$L("ROC");
$L("tajikistan");
$L("tanzania, united republic of");
$L("united republic of tanzania");
$L("tanzania");
$L("thailand");
$L("timor-leste");
$L("east timor");
$L("togo");
$L("tokelau");
$L("tonga");
$L("trinidad and tobago");
$L("trinidad & tobago");
$L("trinidad");
$L("tobago");
$L("tunisia");
$L("turkey");
$L("turkmenistan");
$L("turks and caicos islands");
$L("turks & caicos islands");
$L("turks islands");
$L("caicos islands");
$L("tuvalu");
$L("uganda");
$L("ukraine");
$L("united arab emirates");
$L("uae");
$L("u.a.e.");
$L("dubai");
$L("united kingdom");
$L("uk");
$L("great britain");
$L("gb");
$L("england");
$L("scotland");
$L("wales");
$L("united states");
$L("united states of america");
$L("usa");
$L("united states minor outlying islands");
$L("uruguay");
$L("uzbekistan");
$L("vanuatu");
$L("venezuela, bolivarian republic of");
$L("bolivarian republic of venezuela");
$L("venezuela");
$L("viet nam");
$L("vietnam");
$L("british virgin islands");
$L("virgin islands, british");
$L("bvis");
$L("virgin islands, us");
$L("the us virgin islands");
$L("us virgin islands");
$L("virgin islands");
$L("usvi");
$L("wallis and futuna");
$L("wallis & futuna");
$L("wallis");
$L("futuna");
$L("western sahara");
$L("yemen");
$L("zambia");
$L("zimbabwe");

